version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spinwin-mysql
    restart: always
    env_file:
      - .docker/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spinwin-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: spinwin-nginx
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data: 